### PR TITLE
Tweaked for win10/11

### PR DESCRIPTION
**Pull request by FlannelNZ**
As per previous listed changes. 

New Variable and parameter. Updated Task sequences.
Removed -AcceptLicense for powershellget < 2 statement (it was in both lines).

### CODE REVIEW

**Comment by FlannelNZ** [comment]
Please note I am no PowerShell pro. nor am i a GitHub user, so I have tried my best here.

**Comment by CharlesNRU** [comment]
Hi @FlannelNZ ,

Thanks for the pull request.
Could you please explain the removal of the acceptlicense, I am not sure I understand what is being fixed here.

Also, regarding your task sequence step to detect the windows version when in FullOS, I have a suggestion:
```(Get-CimInstance -ClassName Win32_OperatingSystem | Select-Object -ExpandProperty Caption | Select-String -Pattern "^Microsoft (Windows \S*)").Matches.Groups[1].Value```

The reason for the change is that some people could be using various editions of Windows (Enterprise, Pro, etc.) It could also be localized in different languages. The method above *should* be able to pick up the Windows version correctly no matter what is after "Microsoft Windows XYZ ...."

Other than that it looks really good!

**Comment by FlannelNZ** [comment]
Starting the install-module for MSAL.PS in another process gave me the error -AcceptLicense was an unknown parameter. When I dug back through the log it was reporting version 1.0.0.1, trying to update it, then reporting the same version in $InstalledVersion. Which suggests that it was still trying to use powershellget < 2 in the new process. Possibly because it failed to update the version. So in my case removing the parameter got the command working on powershellget 1.0.0.1. But, maybe It would be better to add another statement to catch 1.0.0.1 elsewhere and use the different install command.



            If((-not $PowerShellGetLatestVersion) -or ($PowerShellGetLatestVersion.Major -lt 2)){
                Add-TextToCMLog $LogFile "Starting another powershell process to install the module..." $component 1
                $result = Start-Process -FilePath powershell.exe -ArgumentList "Install-Module MSAL.PS -AcceptLicense -Force" -PassThru -Wait -NoNewWindow
                If($result.ExitCode -ne 0){
                    Add-TextToCMLog $LogFile "Failed to install MSAL.PS module" $component 3
                    Throw "Failed to install MSAL.PS module"
                }
            }Else{
                Install-Module MSAL.PS -AcceptLicense -Force
            }


Great suggestion on the detection. I will add that to mine. Not sure why they made it so hard to differentiate, honestly.

**Comment by CharlesNRU** [comment]
That works, can I ask you to update the PR? And also the zip file since I do not have access to ConfigMgr to modify the task sequences.

**Comment by FlannelNZ** [comment]
I split out the versions a bit more with some more logging. 
If you see no further issues with that, I can move on with spitting out the task sequence.

**Comment by CharlesNRU** [comment]
I'm honestly not sure about the PowerShellGet stuff.
Do you currently use this solution to authenticate to the AdminService via CMG?
We could merge these changes as-is and update the task sequences but I would like to work on another version of the PowerShell script that doesn't need MSAL.PS at all, it would simplify the script and the task sequence a lot by not needing MSAL.PS and updating PowershellGet and whatnot.

**Comment by CharlesNRU** [comment]
OK, I've committed against your repository. I have removed any dependency on the MSAL.PS module.
Would you be able to test this new version and make sure it still works over CMG?

**Comment by CharlesNRU** [comment]
Hey @bohnanza22, if you would like to test a new version of the script, the script updated in this pull request introduces a new Parameter "DriverPackageWinVer" which should be set as 'Windows 10' or 'Windows 11' to filter for the proper driver package.

Also, I have removed the need for the MSAL.PS module but I would need someone to test and see if it works by accessing the AdminService over CMG.

**Comment by bohnanza22** [comment]
Hi @CharlesNRU I will get this tested in the next few weeks.  Apologies, the timing is a bit weird.  Work and personal things.  But I will need the functionality this provides.  

I have the new version of the script in my test MDM TS Modules I have some small modifications to my TS to accommodate my environment. But those shouldn't interfere with the changes here.  Those mods focus more around what to do if the MDM finds no driver package, since I don't stage fallback packages. 

I imported the zip file from this branch and noticed that the "Manually install MSAL.PS module - WinPE" is still in the "Query AdminService for PackageID" TS. Is this step and the dependency still needed here? or should I disable it for testing? 
 

Also I currently don't have a CMG in my environment. Hopefully we will have one implemented in the next 6 months.  We are working on M365 here so once the Azure stuff gets put in place the CMG should follow soon after.  So I won't be able to test that right away. 

I am super brand new to using Github. I am still trying to wrap my mind around functions and terms. Along with workflows and practical usage.  I am a one man band here at my day job for PS scripting and SCCM/MECM Deployment & TS stuff. So I may have practical questions regarding this platform.

My techs and I use this TS module on the daily and it has been super helpful.  Thanks for being willing to continue supporting it. Also shout out to @FlannelNZ for contributing, hopefully this solves a problem for me before it even becomes a problem.

**Comment by CharlesNRU** [comment]
Hey there, so the MDM-TS.zip file has not been updated with the latest script version yet. I cannot do that myself as I do not have access to a ConfigMgr environment anymore.
Regarding MSAL.PS, the step should not run if you are not using a CMG. However, yes, if the newest version works as expected we won't need any step to pre-install MSAL.PS in the task sequence.

**Comment by FlannelNZ** [comment]
I have updated the Task Sequences and updated the zip. Should be all ready to go.

**Comment by CharlesNRU** [comment]
I updated the Readme a bit, merging now.
Thank you very much for your help on this.

**Comment by bohnanza22** [comment]
I finally got a chance to test this.  Apologies for the timing.  The last few months have been hectic for me. I finally have my Windows 11 test setup.  The new script seems to be working for me.  Thank you to both of you for the work you put into this.

**Pull request merged**
